### ISSUE TITLE
How to correctly configure multiple channels in config.yaml

### ISSUE THREAD

**Issue by 42Network** [sdwilsh/brultech-serial2mqtt#238]
The current README.md has an example for config.yaml that uses a single channel of "- number: 1". How can I use all 7 channels on my ECM-1240, either with the default channel names or my own names? No matter what I try, it seems to only pick up the last item in my channel list to report via MQTT.

Is there supposed to be a hierarchy here, where I need to initially say how many channels there are (7 in my ECM case) and then provide a list of each channel? I've tried working through the voluptuous SCHEMA and can't quite work out how it was intended to customize each channel via YAML for either a GEM or an ECM.

Here is one of my attempts at it. Suggestions?

```
device:
  name: "House Energy Monitor"
  baud: 19200
  type: ECM
  device_com: "COM1"
  channels:
    - number: 1
      name: ChanOne
      type: main
    - number: 2
      name: ChanTwo
      type: main
    - number: 3
      name: ChanThree
      type: normal
```

PS: please note that for now I am bypassing the SET_PACKET_SEND_INTERVAL issue as discussed in #214
